coderefinery/manuals

- workshop-administration.md
> Update guide with more ideas from Espoo

- helping-and-teaching.md
I tried to compile information for helpers.
> add manual for helpers

- README.md
- helping-and-teaching.md
- lesson-design.md
- presenting.md
- teaching-tech-together.md
- workshop-administration.md
I rapidly added a lot of material.  I considered that I was doing too much, and it was too unstructured (and existing repo too minimal) to try to split it out into separate PRs. (sorry about that...)
This is a lot of material I had been meaning to write somewhere.  After being reminded of the manuals repository, I knew had to put it here.  Everything should be considered open for edits, this is a quick and incomplete first draft.
> Major unstructured additions, unorganised

- README.md
- lesson-design.md
- presenting.md
Same as before, quick and unstructured additions everywhere.
> Add more quick, unstructured additions

- helping-and-teaching.md
- lesson-design.md
- teaching-tech-together.md
Additional miscelaneous updates over the last few days.  It's time for someone else to take a look, anyone feel free to remove excessive text.
Closes: #8 (link from both the lesson design page and Teaching Tech Together)
> Unstructured updates

- README.md
- helping-and-teaching.md
- lesson-design.md
- presenting.md
- teaching-tech-together.md
- workshop-administration.md
Very few changes - the material is really good.
> My iteration on the material.

- lesson-design.md
> added a link to Carpentries Curriculum Development Handbook

- helping-and-teaching.md
- presenting.md
- workshop-administration.md
> a few extra points here and there

- presenting.md
after some thining about it, it was previously too rigid
and might have suffocated improvements
> mellow down the part "sticking to material"

- lesson-design.md
- One sticky note suggestion we got was that introduction could always
discuss the current state of affairs.
- This adds a note to carefully consider the introduction, with a
suggestion of discussing current state of affairs first.
- This is opinion-based and needs discussion before merging.
> lesson-design.md: intro/conclusion hints

- presenting.md
As the title says. Add instructions for zsh history tracking.
Preferably put them in a script file.
> Add zsh history tracking

- presenting.md
- I found this was good for reminding me of important fixes I saw as I
was presenting, otherwise I would have forgotton most of the trivial
matters or had to go through all material again.
> presenting: have pad of paper, write down to-dos as presenting

- lesson-design.md
> Minor update: revise how-to-intro a bit

- presenting.md
- This came up in a recent workshop - subtle differences in
implication in how you ask these questions.
> "do you do X?" vs "how do you do Y?" questions

- presenting.md
- This gives more proper ways to do the history tailing on bash, zsh,
and fish.  I couldn't find a preexec function on tcsh.
- These don't handle subshells/ssh
- but they do handle all other known problems with the script-based
solutions.
> Improve tail-history.  Use preexec functions where possible

- workshop-administration.md
Work in progress: marked as draft until I am done - I will hopefully finish today.
> Update documentation about workshop administration

- indico-workshop-management.md
- workshop-administration.md
Here is my sketch for the information about the waiting list that was missing in my opinion. 
I would have discussed this first in a PR as we teach but couldn't open a PR without some modifications in a branch.
I propose to migrate the corresponding google document into repo. Then I propose improvemts to manage a waiting list.
So I assumed a little bit here. Please feel free to reject this if eg. we don't want Indico manual into repo. This didn't take long. :)
> Instruct waiting list, fixes #34

- indico-workshop-management.md
A bit more clarification about waiting list. Will merge myself.
> Clarify waiting list macguyverism a bit more

- presenting.md
used by many software carpentry instructors. 
Tested on macosx, iTerm2 v.3.3.6, tmux 2.9a
> add screencasting option based on tmux

- workshop-administration.md
added a few steps, modified formatting and info for self-organized workshops
> update workshop manual, fixes #28

- lesson-design.md
- lesson-review.md
First draft, but I think it's good enough to start with so that others
can contribute and others can proceed with their work.  I will
continue revising.
> Split into lesson-design.md and lesson-review.md and revise

- tech-docs.md
- This isn't a manual for teaching material, but for the type of docs
you might find to go along with a cluster.  I've highlighted my best
practices, let's see if it's useful to others.
Do you think this is useful here?  I'd like to collect best practices
from across sites, and this is the best place I can think of to do it
(either here or some NordicHPC place that doesn't exist yet).
> tech-docs.md: Add a primitive "tech docs guide"

- README.md
Nothing got removed, just added and rearranged.
> Rearrange README

- indico-workshop-management.md
- scripts/read_csv.py
> add simple script and instructions for extracting registrations from indico

- teaching-tech-together.md
I updated a link that in the summary of Teach Tech Together
(practicing some skills I learnt recently in the coderefinery workshop :) )
> Fix broken link teaching-tech-together.md

- online-training.md
The text can without doubt use more work but I need to move on to the next task ...
> I looked over the text and applied few patches

- zoom-mechanics.md
There is a license file in the repo but I was asked about license and reuse and hope this will make it more visible and clearer.
> add a line about license and reuse

- hackmd-mechanics.md
- It can't hurt to be more clear about how things work.
- Probably some screenshots should be added.
- To review: is this useful?  What else should be added?  I haven't
thought about this too much yet.
> hackmd-mechanics: add page in analogy to zoom-mechanics

- README.md
- helping-and-teaching.md
- Copy + edit from the hackmd.
- This will need to be rebalenced with helpind-and-teaching.md which
sort of covers the same things.  This is about breakout rooms (more
about online), breakout-rooms-groups-help.mdbut can I think the good
parts here can be adapted to in-person, too.
> Copy "hints on breakout rooms" from hackmd into manuals

- README.md
- icebreakers.md
- Copied from Mega-CR "what is a good icebreaker?" answers, so all
participants are credited.
- Also add a few other questions I remember.
> Add sample icebreaker questions

- README.md
- breakout-rooms-helping.md
- Fix broken link
- Add the actual text, which was missing in previous commit!
> breakout-rooms-helping.md: add page

- README.md
- Does this make sense?  I plan on more for the learner section soon.
- To review: not much, make sure that the new sections make sense and
the order is good.
> README: Rearrange the toctree by reader type

- workshop-administration.md
i.e. the regular checklist we use in issues on coderefinery.org,
see e.g. https://github.com/coderefinery/coderefinery.org/issues/444
> add workshop preparation checklist to be used in issue

- hackmd-mechanics.md
- Under "privacy" it said we will leave names in the hackmd, fixed it.
- Revise first paragraph to more clearly say how document is used -
important to frame the privacy implications.
> hackmd-mechanics: the names thing was also mentioned at top

- README.md
- the-project.md
- This tries to cover the basic history and the way the project works
internally, so that others are able to join and take part.
- The page is currently rather lacking and the opinions of one person,
so it needs careful checking and improvement.
- Also, it outlines the kinds of things we need to decide about the
project, since we don't know ourselves yet.
> the-project.md: Initial "about the project"

- README.md
* "These pages document past history, but they don't dictate future.
They are a starting point: feel free to be adventurous.", so that
people don't feel they are constricted to what we say here.  We need
to write down what we have learned, but shouldn't let people think
that future development is done.
* To review: general sanity
> README: Add standard text about history vs future

- README.md
- video-editing.rst
- The purpose of this is to give volunteers who want to process
workshop videos a clear starting point.
- Review: Basic check.  It can probably also use a more detailed
check, too, but that can be incremental.
- @essihe, any thoughts on this?
> video-editing: Add guide on video editing

- video-editing.rst
- Add a formal specification of what we provide and what we want at
the top.
- The purpose of this is to send to someone who can give us a price
estimate for doing the video editing for us.
- This is still somewhat of a draft, but could be merged if reviewers
think it is good.
- Review: is this precies enough for someone to give us that price
estimate?  Of course the actual process will be more agile, but is
this a good starting point?
> video-editing: Add a "specification" at the top

- README.md
- helper-intro.md
- I would like a single landing page for helpers
- Started from @samumantha's intro for a CodeRefinery workshop
- Review: general read is probably enough
> helper-intro: Add new landing page for helpers

- conf.py
- requirements.txt
- Improves web accessibility, until upstream theme is improved
- Review: general, does CI pass?
> Add color contrast module

- README.md
- instructor-tech-setup.md
- presenting.md
- First change to split a page and prepare for a future PR
- Review: general check, this is mainly rearrangement in preparation
for future updates.
> instructors: split tech from other stuff, prepare for future update

- helping-and-teaching.md
> helping-and-teaching: fix chat link, link to chat info

- helper-intro.md
- helping-and-teaching.md
- Make helper-intro the landing point, the rest of the pages support
are linked from there.
- Review: general check
> helpers: rearrange the material a little bit, focus on helper-intro

- README.md
- breakout-rooms-helping.md
- expert-helpers.md
- hackmd-helper.md
- host.md
- instructor-intro.md
- instructor-tech-setup.md
- presenting.md
- This is being revised to be usable as staff and instructor training
material.
- There are many revisions here, but there must be more later - this
isn't fully revised, but making the final version can be an
iterative process.
- Review: a detailed read and review would be good, but also we can
merge and do editing incrementally.
> Large revisions of instructor and staff material

- icebreakers.md
- Thanks to @annefou finding it from carpentries
- Review: minimal
> icebreakers: add another external list

- breakout-rooms-helping.md
- expert-helpers.md
- hackmd-helper.md
- host.md
- Update helper info for HackMD, host, and expert helpers.
- Review: this can use a general read.  It will be iterated later,
this is mostly a semi-factual PR.
> Update advanced helper informtion.

- helper-intro.md
- Fix a link syntax, needs a space
- Review: none
> helper-intro: fix a link

- contributing.md
- Fix a link
- Link to new helper/instructor intros
- Fix an incomplete sentence
- Link to new chat page several places
- Give some examples of what fans can do
- Review: minimal read
> contributing: minor fixups

- chat.md
- Describe some of the new streams that have come up
- Mention muting streams
- Invite other relevant groups to make streams (?)
- Review:
- general
- is the part about other communities making private channels
what we want to say?
> chat: describe more streams, other info on chat

- hackmd-helper.md
- Varius updates based on last week.
- Review: minimal
> hackmd-helper: Misc updates

- instructor-tech-setup.md
- Add IDs to refer to them
- Review: minimal read / does CI pass?
> instructor-tech-setup: Adjust the screenshares descriptions

- Makefile
- chat.md
- conf.py
- contributing.md
- This is a proposal for voting on actions via chat, using emojis and
numbers.
- It's not something that exactly new, and this doesn't say this is
how we actually decide anything.  Instead, it encourages people to
give reactions that can be quantified, in the hopes that we can
reduce uncertainly about making decisions.
- Review: everything, in particular is this a good way to present
things?  Is it even worth presenting things?
> proposal on voting

- README.md
- team-teaching.rst
- New page to describe typical team teaching methods.  As usual, this
doesn't claim to know everything, but tries to give hints based on
what has worked and outline a framework to plan out teach teaching
- Review:
- General check
- See if there are any obvious things missing, but this is a work in
progress.
> team-teaching: new page

- README.md
- online/index.md
- Outline of online teaching guide, trying to organize the different
thoughts I have.
- This is not complete, but is posted to be a starting point for a
general outline.
- Review:
- General check, discuss in meeting, possibly merge and iterate from
there?
> Draft online teaching guide

- README.md
- team-teaching.rst
- Make another pass, clean up both small and large things.
- Almost ready for wide-scale comments now.  My suggestion is to
merge, then we send around for review.
- Review: general check, but it could also use a more detailed
reading now.
> team-teaching: further revisions

- README.md
- obs.rst
- Further revise the OBS guide.  Various cleanups and making a better
exposition.
- It is almost usable now.
- Review: general check, starts to be worth someone making a real pass
(but this can be merged and a real pass done as a second round).
> obs: Further revisions, add to toctree

- team-teaching.rst
(more important changes will come later)
> minor changes in co-teaching manual

- team-teaching.rst
- Focus on models not abstract roles
- Rename the roles to be more unique
- Overall, try to make it more practical and less theoretical.
- Review:
- Someone should give it a good read, but could be done either
before or after committing.  This includes both content and
syntax, I wrote it quickly.
- Again, I have inserted some of my opinions.  These should be
identified and made more general.
> team-teaching: re-work based on review in chat

- team-teaching.rst
> teaching together: give an example for preparation choreography

- obs.rst
- These are small updates I did immediately after RSH.  There is
probably more to come.
- Review: general check.
> obs: Updates after RSH

- README.md
- coderefinery-mooc.rst
- conf.py
- The main audience here is instructors and those organizing a course,
so that they will know what to expect.  It also is the first written
documentation of the plan to us.  The director/producer get training
by other means.
- This initial PR is designed to provide a shared understanding of the
goal.  Then, I go and update the other pages (audiece, helper, etc).
- Review
- Does this make sense to a new reader?
- What important aspects are missing?
- Can we give this to an instructor or organizer and say "This is
what we are doing" ?
- What important information is missing?
> coderefinery-mooc: Add basic description of CR MOOC style

- breakout-rooms-helping.md
- chat.md
- contributing.md
- expert-helpers.md
- hackmd-helper.md
- hackmd-mechanics.md
- helper-intro.md
- helping-and-teaching.md
- how-to-attend-inperson.md
- how-to-attend-online.md
- instructor-intro.md
- teaching-tech-together.md
- zoom-mechanics.md
Working on restructuring the exercise leader material a bit
Main changes so far:
* first tell what exercise leader does and what is expected of him/her
* move 'ways to become more involved' to separate document and link to it
* tbc
Still working on it next few days, therefore draft
Comments/help welcome :)
> Exercise leader material restructuring

- Makefile
- I want to refer to these from another repo (workshop-intro).
> Makefile: Include all images in the build

- README.md
- livestream-teaching.md
- Needed for workshop preparation calls
- To be continued
- Review: general check / automerge
> livestream-teaching: new page focused on livestream teaching practicalities

- how-to-attend-stream.md
- Based on questions from attendees
- Review: quick read, see if anything is missing, merge and iterate
> how-to-attend-stream: Add a section "how it works"

- README.md
- broadcaster.rst
- Focuses on OBS streaming setup
- Relation to other roles
- Setup of OBS
- Allowing others to connect to it
- Preparing for and during each broadcast
- What can go wrong
- Review:
- There is plenty to improve, but I think this is a "merge and iterate" time.
> broadcaster: Add initial draft broadcaster role page

- README.md
- broadcaster.rst
- director.md
- hackmd-helper.md
- host.md
- obs.rst
- online-training.md
- roles-overview.md
- video-checking.rst
- video-editing.rst
- workshop-organizers.md
- Elaborate roles
- Slight reorganization, more renaming pages and marking some old ones
as `OLD`.
- Add some missing role pages (minimal content), or rename them to be
consistent.
- Review: merge and iterate
> Update roles based on existing work

- broadcaster.rst
- Review: automerge, review full page later
> broadcaster: Some practical matters for the broadcaster

- director.md
- roles-overview.md
> Misc updates on various roles pages

- README.md
- video-editor.rst
- Minimal content, to be improved later
- Review: automerge
> Add a "video editor" role page

- indico/setup.md
not to gatekeep but as reset after few people left
we need to figure out a good legal backing to have more people
access to the organization
> adjusted permissions back to me

- chat.md
- Note the per-workshop streams, such as #tools-workshop
- Review: automerge 1day
> chat: Add a note about the per-workshop streams

- README.md
- governance.md
- This is very minimal, but provides a de-facto model of what we do
now.
- I propose that this be improved and merged, and then we have clear
way of improving it in the future (further PRs to this page).
- Review: detailed read and comments
> Add an initial governance document

- local-breakout-rooms.md
> local-breakout-rooms: Fix syntax of included figure

- coderefinery-mooc.rst
- livestream-teaching.md
- Made some time ago but apparently not linked
- Review: automerge
> Add video demo of livestream teaching

- coderefinery-mooc.rst
- online.md
- Also fix some other link syntax
- Review: automerge
> Link 'the future of teaching' video in the right places

- helper-intro.md
- helping-and-teaching.md
- Update the pages related to exercise leader onboarding.
- Review: general check.
> exercise leaders: Update various places for current workshop standards

- instructor-intro.md
- instructors.md
- livestream-teaching.md
- Various small updates for instructor onboarding
- Review: general check
> instructors: Various updates for instructors

- instructor-intro.md
> instructor-intro: Add one more common problem for livestream teaching

- zoom-mechanics.md
- Warnings about differences in livestreams
- Other minor updates
- Review: general check
> zoom-mechanics: Updates based on current practices

- README.md
- outreach.rst
- So far just my summary of the book and personal thoughts, and the
basis of what I will talk about at the kick-off event.
- I propse merge and iterate, both before the event and after.  I may
stil have some more to add before the kick-off.
> outreach: Add outreach plan

- team-teaching.rst
- Give more thoughts that would help a new instructor start.  I'm sure
more will come later, though.
- The point is that the page becomes closer to "send to new
co-instructors to help them understand how things work."
- Ideally the page would be made shorter, but I didn't do that yet.
- Some rst syntax may be slightly wrong, but I will check and fix
after merge.
- Review: general check, or automerge and iterate
> team-teaching: Update for instructor onboarding

- README.md
- co-instructors.md
- This is made to help start off co-instructors, basically a way to
help them get started.
- Not done yet, I am sure there is a lot more needed.
- Review: quick check, can already be merged and we will iterate.
> co-instructors: Add starting page for co-instructors

- tech-docs.md
mentioning Shpinx and Markdown
> Added link to Documentation lesson

- requirements.txt
This is really useful for local preview.
> require also sphinx-autobuild

- instructor-tech-setup.md
- Based on what I have seen and what I think we like collectively.
Some of my opinions may be in here, but I haven't tried to do only
what I think.
- Reformat the page to be more clear and have more, but shorter,
sections.
- Perhaps most controversial is hiding most of the prompt history
options and focusing on prompt-log.
- Review: suggest automerge and then revise on the page, viewing diff
may be difficult.
> instructor-tech-setup: Update with my understanding of best practices

- instructor-tech-online.md
- instructor-tech-setup.md
- Extra small changes after a day and seeing the real thing.  Close to
done, I think.
- Review: automerge and iterate
> instructor-tech-setup: further incremental revisions

- how-to-attend-stream.md
- Mostly the same as what the workshop pages had, but it's relevant to
other courses so copied here.
- Review: worth a read, I probably have forgotten some things, too.
> how-to-attend-stream: Copy accessibility notes from CR workshop pages

- workshop_playbook.md
Based on: https://hackmd.io/@coderefinery/2022-sep-ws-planning
Currently only copied material from the HackMD, now continuing working on refining and maybe (?) merging with workshop-administration.
This PR is currently only FYI that someone is working on this :)
> Playbook for workshop organization

- coderefinery-mooc.rst
- coderefinery-mooc/mooc-diagram.svg
- exercise-leaders.md
- expert-helpers.md
- how-to-attend-inperson.md
- how-to-attend-online.md
- how-to-attend-stream.md
- indico/online.md
- instructor-intro.md
- instructor-stream.md
- instructors.md
- local-breakout-rooms.md
- online.md
- outreach.rst
- presenting.md
- roles-overview.md
- workshop-organizers.md
- workshop-playbook.md
There's just issues with some capitals
> Changed ELs to TLs

- workshop-playbook.md
Based on discussions at AHM meeting and some extra thoughts.
Incuding spoilers suggested by Thomas.
If this seems ok for you, I would go on and update the role pages to clearly state what are the responsibilities of each role and make sure they match with the checkboxes in this template and are explained a bit more if needed. Every role mentioned in this hackmd template should then also link to the corresponding role page. Some of which do not exist currently.
As usual feel free to edit or disregard.
> Suggestion for updated HackMD template

- team-leaders.md
- Perhaps the most important one is that main job of team leaders is
to project excitement to the others and energize them.
- Misc other updates throughout, mostly small.
> team-leaders: Misc updates

- instructors.md
- registration-coordinator.md
- workshop-playbook.md
Still some roles could use those timing information
> Update from mar23 hackmd

- workshop-playbook.md
- shorter
- some simplification
- detailed schedules moved to lesson repos
> update the playbook/checklist

- team-leaders.md
typo fixes, slight shortening, reorganize where I thought it was helpful
> gone through team leader onboarding

- README.md
- onboarding.md
On Monday we might have a new person joining the team meeting (not just instructor, but team member). 
This could be used as "first steps" document? 
Please check is something very important is missing :)
> Add new people onboarding page draft

- onboarding.md
- sorry forgot that part before.
> Make links clickable

- README.md
- ambassadors.md
to be linked then to CR webpage?
> Add ambassadors manual page

- .github/workflows/spellcheck.yml
- ambassadors.md
- chat.md
- instructors.md
- meeting-checklist.rst
- team-leaders.md
- workshop-organizers.md
- workshop-playbook.md
In different places we have old channel names or channels named streams. 
This PR proposes to fix to new naming.
> Update Chat channel names
