README.md, workshop-administration.md, workshop-requirements-inperson.md
- This copies the requirements to manuals and adds an introduction,
but doesn't yet remove it from the website or change the website
links.
- To check: It seems like this is a logical place to put this - what
do you all think?
=> Copy workshop-requirements from coderefinery.org to manuals

workshop-administration.md
- remove duplication with instructor training, move the missing things
here.
- To review: not much, I think.  Direct copies.  There might be some
duplication or something missing, but I think not worth checking too
much.
=> workshop-administration: copy things from instructor training

README.md
- Classify things into checklist, reference, tutorial.
- To check: last night I thought this would be a good idea, but I'm
not so sure anymore.  But, it might be useful whene we start having
muliple pages on a certain topic, for example a tutorial to get
people started, but also a checklist.
- Anyway, don't merge this unless someone *really* likes it, we can
wait a week and decide.
- Alternative 1: don't have multiple pages on a certain topyc
- Alternative 2: title makes it clear what is on the page (I am
thinking this is best now - not this PR)
=> README: for each page, list the type of material

zoom-mechanics.md
- Muting is one of the things that slows down discussions.  During
breakout sessions, it's OK if you stay unmuted if you are in a quiet
enough place or have high-quality equipment.  This will make
breakout rooms more like a discussion and less like a radio
conversation, I think.
- We should encourage people to put some effort into finding a quiet
place or getting equipment.  Of course not everyone can, but we can
at least point out it's worth making an effort.
- This is only step one of this process.
=> zoom-mechanics: de-emphasize constant muting during discussions

zoom-mechanics.md
- When presenting this, the presenter shouldn't spend too much time,
but note that it can be done
- This can be updated into a section on "how to take part in
{online|inperson} lessons", which tells people how to mentally and
physically prepare to make the most of it.  I think it needs to be
said.
=> zoom-mechanics: note how you can avoid fullscreen mode

README.md, how-to-attend-inperson.md, how-to-attend-online.md
[draft until the sphinx stuff is accepted, then needs TOC linking]
- how-to-attend-online: how to successfully take part online.
- how-to-attend-inperson: same, but for inperson
- Copied from mega-CR and Finland HPC kickstart general information
and lessons learned.
- This is not designed to replace installation instructions, but more
general mental and physical preparation.  Should this me moved to
installation instructions sometime?
- To review: deserves a detailed reading to make sure things are what
we agree on, typographical errors, and to ensure it general positive
message and doesn't demotivate people.
=> how-to-attend: add pages based on recent online workshops

zoom-mechanics.md
- Must use proper syntax, so that Spinx will know it's an image and
copy it to the final output.
- Also add alt text to images.
=> zoom-mechanics: Convert `<img>` to markdown image syntax

zoom-mechanics.md
- Remove duplicate table of contents at the top (now handled by
sphinx, at least one link had changed)
- adjust heading levels
- but all status indicators under one section
- section for other points at the end
- to review:
- basic sanity check, should be nothing objectionable
=> zoom-mechanics: Adjust table of contents

zoom-mechanics.md
- Add a few text descriptions, so that someone can understand even if
they can't see images.
- Also bold the names of buttons to click.
- To review: ensure all the text makes sense.
=> zoom-mechanics: Add test descriptions for non-image readers

README.md, contributing.md
- This started as a way to present "packaging" of contributing which
can be presented to your supervisors/organizations, to try to make
CodeRefinery a part of your job.  I think this is the main benefit
of this section, we aren't advanced enough that we need to give
people to participate in other ways.
- But it does include some other ideas about how to contribute.  My
goal right now isn't to make it a generic "how to contribute to an
open source project" thing.
- To review: right now, everything.  This is a quick draft.  Is it too
verbose?  Is it too patronizing?  Are these even ways we expect
people to contribute?  Each "package" needs thought and elaboration,
we need to make a good case to the supervisor about it.  And in
reality, someone will contribute in multiple ways - is that …
=> contributing: Add draft page on contributing to coderefinery

indico-workshop-management.md, online-training.md, workshop-administration.md
- Commonmark requires `<http://example.com/>` with the angle brackets
to auto-detect a link.
=> Fix md http links

contributing.md
- Note that manuals are for the past, and not everything has to be
done the same way.
- By the same token, make a clear suggestion that someone can try to
do something the same as usual (follow manuals, mentors), and then
improve things the next time they do it?
=> contributing: Add note that manuals document past, not specify future

how-to-attend-online.md
- This makes the workshop page much shorter.
- Most of this is copied from the may 2020 page.
- Review: general check, already linked from october 2020
=> how-to-attend-online: Copy "how to live stream" from workshop page

instructor-tech-setup.md
For setting up a two-pane tmux with shell history.
=> Add a `tmuxp` configuration to instructors manual

instructor-intro.md
- Adjust instructor-intro with more information about the bigger
picture of being an instructor and getting more involved.
- Perhaps the section and page shouldn't be labeled as just "for
instructors", but some more general term that describes all of the
roles beyond helper, since that is the section is about now.
- Review: does this pathway match what we want?  Is it attractive to
those who would want to join?
=> instructor-intro: Add a pathway to becoming involved

README.md, instructor-intro.md, workshop-prep-call.md
- Make a dedicated "workshop prepa call" page, separate from
instructor-intro.
- Add "top issues new instructors face".
- Misc new things added
- Review: this is worth reading, though parts have already been read
in other contexts (instructor training).  Still, this is only one
part of an iteration.
=> instructor intro: More comments from last week

README.md, breakout-rooms-helping.md, expert-helpers.md, hackmd-helper.md, hackmd-mechanics.md, helper-intro.md, helping-and-teaching.md, how-to-attend-inperson.md, instructor-intro.md
Updating the helper manuals:
1. replaced helper with exercise leader
In some places in the text I left the helper or added / exercise leader
2. added info on how to prepare hackmd before the course, with info to enable editing by anyone without login
3. added info for learners that they do not need to login to edit the hackmd
2. and 3. close #145
=> Helper manual fixes

zoom-mechanics-old.md
- Remove `how-to-zoom` from zoom-mechanics-old, it is now in
zoom-mechanics (the new one).
=> zoom-mechanics-old: Remove now-unneeded reference target

README.md, how-to-attend-inperson.md, how-to-attend-stream.md
- Update and make these pages consistent (using diffing between them
and porting improvements in one to others)
- how-to-attend-livestream: Add a new page, based on
how-to-attend-online.  This is copy-and-paste and modification,
using a graphical diff tool.  I am a bit unhappy how there are three
similar pages now, perhaps we can combine them using sphinx-tabs later.
- Remove some 'general prep' stuff (shell, git, etc), it is now also
in the template-workshop-webpage.  This is workshop specific, and
these pages are becoming more generic and will be linked from many
different workshops (like python-for-scicomp).
- Review:
- Overall probably doesn't need too much review, instead merge +
iterate.
- how-to-attend-{inperson,online}: These can be directly checked
using the github diffs.  There …
=> how-to-attend-*: Update pages, add livesteam page

README.md, contributing.md, local-breakout-rooms.md, open-your-courses.md
- Make the contributing page much shorter and to the point
- Focus it on three actions from a chat message: join instructor
training, advertise our workshops, and open your own teaching.
- Make landing pages for "advertise our workshops"
(local-breakout-rooms.md) and opening your own teaching
(open-your-courses.md).  These can be linked from other places.
- I plan to copy these three actions from contributing.md to
https://coderefinery.org/organization/get-involved/ almost verbatim,
and make the rest of that page much shorter (maybe move all of it to
a manuals page - or just remove it and re-add it later, since most
seems to be covered in these three categories.)  This will be later,
and I'll try to make sure that nothing important gets lost.
- Review: automerge and improve
=> Rework the contributing page

indico/setup.md
this could lead to administrators from older events having access
to new events
=> when creating new events, do not copy ACLs

exercise-leaders.md
@samumantha here an attempt to make this one page that can be presented but also avoids repetition.
I hope I changed it towards the better. It is probably impossible to see this from the diff below and I recommend to merge and check the rendered page.
It is hopefully not too lengthy. I have tried to emphasize important points and some sections at the end can be skipped in an on-boarding session.
=> merge the onboarding with EL background info

workshop-playbook.md
I removed the list of names from CodeRefinery Zoom Exercise/Team Leaders and added some explanation. Idea was that they would be needed if we did form the teams in situ. Feel free to reformat.
I put the description links under the headline.
Added one missing crosslink between the roles (outreach and marketing coordinator)
=> removed CR ELs + minor fixes
